fix: add key_to_nodes to managed_ring and worker
bitwalker/libring pull request #33
Opened 2023-11-26 05:28 UTC by MikaAK

Just adding key_to_nodes to allow for replicas

2024-05-30 15:01 UTC, bitwalker requested changes
Looks good, just one small tweak and I can get this merged

2024-05-30 15:01 UTC, bitwalker commented on lib/managed_ring.ex
> +  Maps a key to a node on the hash ring.
*Nit:* Rephrase this to "Maps a key to a set of nodes on the hash ring"

2024-06-19 18:54 UTC, MikaAK commented on lib/managed_ring.ex
> +  Maps a key to a node on the hash ring.
Done! Sorry for such a long delay @bitwalker I wasn't checking my github notifications 😆

2024-09-17 17:26 UTC, bitwalker approved these changes

2024-09-17 17:26 UTC, merged